name: Release

on:
  workflow_run:
    workflows: ['validate']
    branches: [main]
    types:
      - completed
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '.github/workflows/release.yaml'

permissions:
  contents: write
  issues: write
  id-token: write
  packages: write

concurrency:
  group: release-${{ github.ref }}

jobs:
  run:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Use Node.js LTS
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          # https://nodejs.org/en/about/previous-releases#release-schedule
          # Active LTS
          node-version: 24

      - uses: taiki-e/install-action@a164de717a0ee9284c2d9db1c6016a4c339cd333 # v2.69.14
        with:
          tool: just

      - name: Setup Project
        run: just setup

      - name: Release it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: just release-it
